Corruption after 155 iterations
System.InvalidOperationException: Cannot perform save because document users/1-A has been modified by the session and is also taking part in deferred PATCH command
   at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.ThrowInvalidModifiedDocumentWithDeferredCommand(ICommandData resultCommand) in /home/ubuntu/src/ravendb/src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs:line 1177
   at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.PrepareForEntitiesPuts(SaveChangesData result) in /home/ubuntu/src/ravendb/src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs:line 1095
   at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.PrepareForSaveChanges() in /home/ubuntu/src/ravendb/src/Raven.Client/Documents/Session/InMemoryDocumentSessionOperations.cs:line 880
   at Raven.Client.Documents.Session.Operations.BatchOperation.CreateRequest() in /home/ubuntu/src/ravendb/src/Raven.Client/Documents/Session/Operations/BatchOperation.cs:line 34
   at Raven.Client.Documents.Session.DocumentSession.SaveChanges() in /home/ubuntu/src/ravendb/src/Raven.Client/Documents/Session/DocumentSession.cs:line 97
   at SlowTests.Issues.RavenDB_11089.CanIncrement(RavenTestParameters config) in /home/ubuntu/src/ravendb/test/SlowTests/Issues/RavenDB-11089.cs:line 1256
   at Tryouts.Program.Main(String[] args) in /home/ubuntu/src/ravendb/test/Tryouts/Program.cs:line 47